'use strict';
// Constantes de comando de bordado.
// Portado de pystitch (MIT, inkstitch/pystitch) — valores idênticos ao EmbConstant.py.

module.exports = {
  COMMAND_MASK: 0x000000ff,
  FLAGS_MASK: 0x0000ff00,

  NO_COMMAND: -1,
  STITCH: 0,
  JUMP: 1,
  TRIM: 2,
  STOP: 3,
  END: 4,
  COLOR_CHANGE: 5,
  SEQUIN_MODE: 6,
  SEQUIN_EJECT: 7,
  NEEDLE_SET: 9,
  SLOW: 0x0b,
  FAST: 0x0c,

  SEW_TO: 0xb0,
  NEEDLE_AT: 0xb1,
  STITCH_BREAK: 0xe0,
  SEQUENCE_BREAK: 0xe1,
  COLOR_BREAK: 0xe2,
  TIE_ON: 0xe4,
  TIE_OFF: 0xe5,
  FRAME_EJECT: 0xe9,

  OPTION_MAX_STITCH_LENGTH: 0xd5,
  OPTION_MAX_JUMP_LENGTH: 0xd6,
  OPTION_EXPLICIT_TRIM: 0xd7,
  OPTION_IMPLICIT_TRIM: 0xd8,

  CONTINGENCY_TIE_ON_NONE: 0xd3,
  CONTINGENCY_TIE_ON_THREE_SMALL: 0xd1,
  CONTINGENCY_TIE_OFF_NONE: 0xd4,
  CONTINGENCY_TIE_OFF_THREE_SMALL: 0xd2,

  CONTINGENCY_LONG_STITCH_NONE: 0xf0,
  CONTINGENCY_LONG_STITCH_JUMP_NEEDLE: 0xf1,
  CONTINGENCY_LONG_STITCH_SEW_TO: 0xf2,

  CONTINGENCY_SEQUIN_UTILIZE: 0xf5,
  CONTINGENCY_SEQUIN_JUMP: 0xf6,
  CONTINGENCY_SEQUIN_STITCH: 0xf7,
  CONTINGENCY_SEQUIN_REMOVE: 0xf8,
};
